# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 16:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Dimension',
                'verbose_name_plural': 'Dimensions',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_edge_objects', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='thesaurus.Dimension', verbose_name='Dimension')),
            ],
            options={
                'verbose_name': 'Relação',
                'verbose_name_plural': 'Relações',
            },
        ),
        migrations.CreateModel(
            name='FacetIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Rótulo Nodal',
                'verbose_name_plural': 'Rótulos Nodais',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('label', models.TextField(unique=True, verbose_name='Termo')),
                ('apps', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='Comma-separated list of apps that can use this term.', size=None, verbose_name='Disponibilidade nas bases')),
                ('children', models.ManyToManyField(related_name='parents', through='thesaurus.Edge', to='thesaurus.Node', verbose_name='Termos específicos')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_node_objects', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_node_objects', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Termo',
                'verbose_name_plural': 'Termos',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Título da nota')),
                ('contents', models.TextField(verbose_name='Conteúdo da nota')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='thesaurus.Node', verbose_name='Termo')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tesauro',
                'verbose_name_plural': 'Tesauros',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='thesaurus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='thesaurus.Thesaurus', verbose_name='Tesauro'),
        ),
        migrations.AddField(
            model_name='facetindicator',
            name='for_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_indicators', to='thesaurus.Node', verbose_name='Termo'),
        ),
        migrations.AddField(
            model_name='edge',
            name='end_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='thesaurus.Node', verbose_name='Termo específico'),
        ),
        migrations.AddField(
            model_name='edge',
            name='facet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_edges', to='thesaurus.FacetIndicator', verbose_name='Rótulo nodal'),
        ),
        migrations.AddField(
            model_name='edge',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_edge_objects', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='edge',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edges', to='thesaurus.Node', verbose_name='Termo genérico'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='thesaurus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='thesaurus.Thesaurus', verbose_name='Tesauro'),
        ),
    ]
