# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 22:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edge',
            options={'verbose_name': 'Relação', 'verbose_name_plural': 'Relações'},
        ),
        migrations.AlterModelOptions(
            name='facetindicator',
            options={'verbose_name': 'Rótulo Nodal', 'verbose_name_plural': 'Rótulos Nodais'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Termo', 'verbose_name_plural': 'Termos'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='thesaurus',
            options={'verbose_name': 'Tesauro', 'verbose_name_plural': 'Tesauros'},
        ),
        migrations.AddField(
            model_name='facetindicator',
            name='label',
            field=models.TextField(default='', verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edge',
            name='end_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='thesaurus.Node', verbose_name='Termo específico'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='facet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_edges', to='thesaurus.FacetIndicator', verbose_name='Rótulo nodal'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edges', to='thesaurus.Node', verbose_name='Termo genérico'),
        ),
        migrations.AlterField(
            model_name='facetindicator',
            name='for_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_indicators', to='thesaurus.Node', verbose_name='Termo'),
        ),
        migrations.AlterField(
            model_name='node',
            name='apps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='Comma-separated list of apps that can use this term.', size=None, verbose_name='Disponibilidade nas bases'),
        ),
        migrations.AlterField(
            model_name='node',
            name='children',
            field=models.ManyToManyField(related_name='parents', through='thesaurus.Edge', to='thesaurus.Node', verbose_name='Termos específicos'),
        ),
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.TextField(unique=True, verbose_name='Termo'),
        ),
        migrations.AlterField(
            model_name='node',
            name='thesaurus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='thesaurus.Thesaurus', verbose_name='Tesauro'),
        ),
        migrations.AlterField(
            model_name='note',
            name='contents',
            field=models.TextField(verbose_name='Conteúdo da nota'),
        ),
        migrations.AlterField(
            model_name='note',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='thesaurus.Node', verbose_name='Termo'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True, verbose_name='Título da nota'),
        ),
        migrations.AlterField(
            model_name='thesaurus',
            name='name',
            field=models.TextField(verbose_name='Nome'),
        ),
    ]
