# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 20:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edge',
            options={'verbose_name': 'Edge', 'verbose_name_plural': 'Edges'},
        ),
        migrations.AlterModelOptions(
            name='facetindicator',
            options={'verbose_name': 'Facet Indicator', 'verbose_name_plural': 'Facet Indicators'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Term', 'verbose_name_plural': 'Terms'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='thesaurus',
            options={'verbose_name': 'Thesaurus', 'verbose_name_plural': 'Thesauri'},
        ),
        migrations.AlterField(
            model_name='dimension',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='thesaurus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='thesaurus.Thesaurus', verbose_name='Thesaurus'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='thesaurus.Dimension', verbose_name='Dimension'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='end_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='thesaurus.Node', verbose_name='Child term'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='facet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_edges', to='thesaurus.FacetIndicator', verbose_name='Facet indicator'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edges', to='thesaurus.Node', verbose_name='Parent term'),
        ),
        migrations.AlterField(
            model_name='facetindicator',
            name='for_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_indicators', to='thesaurus.Node', verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='facetindicator',
            name='label',
            field=models.TextField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='node',
            name='apps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='Comma-separated list of apps that can use this term.', size=None, verbose_name='App availability'),
        ),
        migrations.AlterField(
            model_name='node',
            name='children',
            field=models.ManyToManyField(related_name='parents', through='thesaurus.Edge', to='thesaurus.Node', verbose_name='Child terms'),
        ),
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.TextField(unique=True, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='node',
            name='thesaurus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='thesaurus.Thesaurus', verbose_name='Thesaurus'),
        ),
        migrations.AlterField(
            model_name='note',
            name='contents',
            field=models.TextField(verbose_name='Note contents'),
        ),
        migrations.AlterField(
            model_name='note',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='thesaurus.Node', verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True, verbose_name='Note title'),
        ),
        migrations.AlterField(
            model_name='thesaurus',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
