# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesaurus', '0002_auto_20170911_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_correlation_objects', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correlations', to='thesaurus.Dimension', verbose_name='Dimension')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_from+', to='thesaurus.Node', verbose_name='Parent term')),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_correlation_objects', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_to+', to='thesaurus.Node', verbose_name='Child term')),
            ],
            options={
                'verbose_name': 'Correlation',
                'verbose_name_plural': 'Correlations',
            },
        ),
        migrations.AlterField(
            model_name='edge',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edges', to='thesaurus.Dimension', verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='node',
            name='correlations',
            field=models.ManyToManyField(related_name='_node_correlations_+', through='thesaurus.Correlation', to='thesaurus.Node', verbose_name='Correlated terms'),
        ),
    ]
