# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0003_auto_20170911_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_from+', to='thesaurus.Node', verbose_name='Correlated term'),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_to+', to='thesaurus.Node', verbose_name='Correlated term'),
        ),
    ]
