# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0004_auto_20170911_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edge',
            options={'ordering': ('start_node', 'dimension', 'ordering'), 'verbose_name': 'Edge', 'verbose_name_plural': 'Edges'},
        ),
        migrations.AlterModelOptions(
            name='facetindicator',
            options={'ordering': ('for_node', 'ordering'), 'verbose_name': 'Facet Indicator', 'verbose_name_plural': 'Facet Indicators'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['node', 'ordering'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.RemoveField(
            model_name='node',
            name='correlations',
        ),
        migrations.AddField(
            model_name='dimension',
            name='correlation_init',
            field=models.CharField(default='a', max_length=20, unique=True, verbose_name='Sigla de Termos Relacionados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimension',
            name='edge_end_init',
            field=models.CharField(default='b', max_length=20, unique=True, verbose_name='Sigla de Termos Específicos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimension',
            name='edge_start_init',
            field=models.CharField(default='c', max_length=20, unique=True, verbose_name='Sigla de Termos Genéricos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edge',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='facetindicator',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='node',
            name='correlated',
            field=models.ManyToManyField(related_name='_node_correlated_+', through='thesaurus.Correlation', to='thesaurus.Node', verbose_name='Correlated terms'),
        ),
        migrations.AddField(
            model_name='note',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='thesaurus.Node', verbose_name='Correlated term'),
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together=set([('start_node', 'end_node', 'dimension'), ('start_node', 'ordering', 'dimension')]),
        ),
        migrations.AlterUniqueTogether(
            name='facetindicator',
            unique_together=set([('ordering', 'for_node'), ('label', 'for_node')]),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set([('node', 'ordering')]),
        ),
    ]
