# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0005_auto_20170912_1111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together=set([('start_node', 'end_node', 'dimension')]),
        ),
        migrations.AlterUniqueTogether(
            name='facetindicator',
            unique_together=set([('label', 'for_node')]),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set([]),
        ),
    ]
