# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0007_auto_20170912_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='facetindicator',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
