# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0008_auto_20170912_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edge',
            options={'ordering': ('start_node', 'dimension', 'ordering'), 'verbose_name': 'Edge', 'verbose_name_plural': 'Edges'},
        ),
        migrations.AlterModelOptions(
            name='facetindicator',
            options={'ordering': ('for_node', 'ordering'), 'verbose_name': 'Facet Indicator', 'verbose_name_plural': 'Facet Indicators'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['node', 'ordering'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
