# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0009_auto_20170912_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='should_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_for', to='thesaurus.Node', verbose_name='Should use'),
        ),
    ]
