# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesaurus', '0010_node_should_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
            ],
            options={
                'verbose_name': 'Used for',
                'verbose_name_plural': 'Used for',
            },
        ),
        migrations.RemoveField(
            model_name='node',
            name='should_use',
        ),
        migrations.AddField(
            model_name='usedfor',
            name='allowed_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='thesaurus.Node', verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='usedfor',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_usedfor_objects', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='usedfor',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_usedfor_objects', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='usedfor',
            name='verbotten_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prohibition', to='thesaurus.Node', unique=True),
        ),
        migrations.AddField(
            model_name='node',
            name='used_for',
            field=models.ManyToManyField(related_name='should_use', through='thesaurus.UsedFor', to='thesaurus.Node', verbose_name='Used for'),
        ),
    ]
