# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0011_auto_20170912_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='correlation_init',
            field=models.CharField(max_length=20, unique=True, verbose_name='Initials for Correlated Terms'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='edge_end_init',
            field=models.CharField(max_length=20, unique=True, verbose_name='Initials for Specific Terms'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='edge_start_init',
            field=models.CharField(max_length=20, unique=True, verbose_name='Initials for Generic Terms'),
        ),
        migrations.AlterField(
            model_name='usedfor',
            name='allowed_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='thesaurus.Node'),
        ),
        migrations.AlterField(
            model_name='usedfor',
            name='verbotten_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prohibition', to='thesaurus.Node', unique=True, verbose_name='Term'),
        ),
    ]
