# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0013_auto_20170912_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='correlation_init',
            field=models.CharField(default='RT', max_length=20, verbose_name='Initials for Correlated Terms'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='edge_end_init',
            field=models.CharField(default='ST', max_length=20, verbose_name='Initials for Specific Terms'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='edge_start_init',
            field=models.CharField(default='GT', max_length=20, verbose_name='Initials for Generic Terms'),
        ),
    ]
