# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0014_auto_20170912_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='facet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_edges', to='thesaurus.FacetIndicator', verbose_name='Facet indicator'),
        ),
    ]
